services:
  - type: web
    name: cashflow-explainer-api
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_MODEL
        value: llama-3.3-70b-versatile
      - key: CHAT_PROVIDER
        value: groq
      - key: CHAT_MODEL
        value: llama-3.3-70b-versatile
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "30"
      - key: REFRESH_TOKEN_EXPIRE_DAYS
        value: "7"
      - key: CORS_ORIGINS
        value: https://cashflow-pi-liard.vercel.app
      - key: DATABASE_URL
        fromDatabase:
          name: cashflow-db
          property: connectionString

databases:
  - name: cashflow-db
    plan: free
    databaseName: cashflow
    user: cashflow
